CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash BLOB NOT NULL,
    activated INTEGER NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
	);